### PR TITLE
removed TMPE NC old integration code.

### PR DESCRIPTION
**Pull request by kianzarrin**
test with: TMPE 11.5.2  that has implemented `MoveITIntegrationBase` :
https://ci.appveyor.com/api/projects/krzychu124/tmpe/artifacts/TMPE.zip?branch=MoveIT-Integration

TMPE PR: https://github.com/CitiesSkylinesMods/TMPE/pull/1005

PS:
some redundant TMPE NC translations remain.

### CODE REVIEW

**Review by Quboid — CHANGES_REQUESTED** [review]
Two issues:
 - Is the LaneIDs section in MoveableSegment.cs still required?
 - In MoveIt.csproj, German and Chinese language files now have a SubType defined. Is this intended?

**Comment by kianzarrin** [comment]
> @Quboid Is the LaneIDs section in MoveableSegment.cs still required?

Yes it is. I did notice that you mark it as deprecated but you need the lane IDs to generate the `InstanceID->InstanceID` map you pass to `Paste()` to map the lanes.

EDIT:
```
CloneAction.cs:
                            for (int i=0;i< clonedLaneIds.Count; ++i)
                            {
                                var lane0 = new InstanceID { NetLane = segmentState.LaneIDs[i] };
                                var lane = new InstanceID { NetLane = clonedLaneIds[i] };
                                // Debug.Log($"Mapping lane:{lane0.NetLane} to {lane.NetLane}");
                                InstanceID_origToClone.Add(lane0, lane);
                            }
```

**Comment by kianzarrin** [comment]
> In MoveIt.csproj, German and Chinese language files now have a SubType defined. Is this intended?

Sorry my bad. that is not intentionall. I don't know what to do with these languages. can you please take care of them?

**Comment by Quboid** [comment]
OK, this all sounds good. I'll take care of the language files.

**Review by Quboid — APPROVED** [review]

**Pull request merged**
